---
- hosts: test_machine
  become: yes

  pre_tasks:
  - apt:
      name: python-docker
      update_cache: yes
    changed_when: false

  post_tasks:
  - apt:
      name: python-docker
      state: absent
      purge: yes
    changed_when: false

  roles:
    - role: '.'
      email: XXXX@gmail.com
      www_volume: /srv/docker/letsencrypt/www
