---
- name: Check 'letsencrypt_working_directory' parameter
  assert:
    that:
      - "letsencrypt_working_directory is defined"
      - "letsencrypt_working_directory | length > 0"
    fail_msg: "parameter 'letsencrypt_working_directory' is missing"

- name: Check 'letsencrypt_volume' parameter
  assert:
    that:
      - "letsencrypt_volume is defined"
      - "letsencrypt_volume | length > 0"
    fail_msg: "parameter 'letsencrypt_volume' is missing"

- name: Check 'letsencrypt_www_volume' parameter
  assert:
    that:
      - "letsencrypt_www_volume is defined"
      - "letsencrypt_www_volume | length > 0"
    fail_msg: "parameter 'letsencrypt_www_volume' is missing"

- name: Check 'letsencrypt_config_volume' parameter
  assert:
    that:
      - "letsencrypt_config_volume is defined"
      - "letsencrypt_config_volume | length > 0"
    fail_msg: "parameter 'letsencrypt_config_volume' is missing"

- name: Check 'letsencrypt_data_volume' parameter
  assert:
    that:
      - "letsencrypt_data_volume is defined"
      - "letsencrypt_data_volume | length > 0"
    fail_msg: "parameter 'letsencrypt_data_volume' is missing"

- name: Check 'letsencrypt_log_folder' parameter
  assert:
    that:
      - "letsencrypt_log_folder is defined"
      - "letsencrypt_log_folder | length > 0"
    fail_msg: "parameter 'letsencrypt_log_folder' is missing"

- name: Check site parameter
  include: check-site-parameters.yml
  with_items: "{{ letsencrypt_sites }}"
