---
- name: create config directory
  file:
    path: "{{ letsencrypt_config_volume }}"
    state: directory
    owner: root
    group: root
    mode: 0750

- name: create data directory
  file:
    path: "{{ letsencrypt_data_volume }}"
    state: directory
    owner: root
    group: root
    mode: 0750

- name: create log directory
  file:
    path: "{{ letsencrypt_log_folder }}"
    state: directory
    owner: root
    group: root
    mode: 0750
