---
- name: create config directory
  file:
    path: "{{ config_volume }}"
    state: directory
    owner: root
    group: root
    mode: 0750

- name: create data directory
  file:
    path: "{{ data_volume }}"
    state: directory
    owner: root
    group: root
    mode: 0750

- name: create log directory
  file:
    path: "{{ log_folder }}"
    state: directory
    owner: root
    group: root
    mode: 0750
