---
- name: create config directory
  file:
    path: "{{config_volume}}"
    state: directory
    owner: root
    group: root
    mode: 775
  when: config_volume != ''

- name: create data directory
  file:
    path: "{{data_volume}}"
    state: directory
    owner: root
    group: root
    mode: 775
  when: data_volume != ''
