---
- name: pull image
  docker_image:
    name: "{{image_name}}:{{image_version}}"

- include: create_volumes.yml

- name: Create script path
  file:
    path: "{{script_path}}"
    state: directory
    mode: 0755

- name: Create create_cert script
  template:
    src: create_cert.bash.j2
    dest: "{{create_cert_script_path}}"
    mode: 0755

- name: Create renew service
  template:
    src: systemd/letsencrypt.renew.service.j2
    dest: "/etc/systemd/system/{{renew_service_name}}.service"
    owner: root
    group: root
    mode: 0554
  register: letsencrypt_renew_service

- name: Setup renew service
  systemd:
    name: "{{renew_service_name}}.service"
    state: stopped
    enabled: yes

- name: Create renew timer
  template:
    src: systemd/letsencrypt.renew.timer.j2
    dest: "/etc/systemd/system/{{renew_service_name}}.timer"
    owner: root
    group: root
    mode: 0554
  register: letsencrypt_renew_timer

- name: Setup renew timer
  systemd:
    name: "{{renew_service_name}}.timer"
    state: started
    enabled: yes

- include: create_certificate.yml site_name={{ item }}
  with_items: "{{ domains }}"

- name: Reload systemd
  command: systemctl daemon-reload
  when: letsencrypt_renew_service.changed or letsencrypt_renew_timer.changed
