---
- name: Enable renew service
  systemd:
    name: "{{ letsencrypt_renew_service_name }}.service"
    enabled: true
    daemon_reload: true
  when: not (
    molecule_docker_environment is defined
    and molecule_docker_environment | bool
    )

- name: Enable renew timer
  systemd:
    name: "{{ letsencrypt_renew_service_name }}.timer"
    enabled: true
    daemon_reload: true
  when: not (
    molecule_docker_environment is defined
    and molecule_docker_environment | bool
    )

- name: Start renew timer
  systemd:
    name: "{{ letsencrypt_renew_service_name }}.timer"
    state: started
    daemon_reload: true
  when: not (
    molecule_docker_environment is defined
    and molecule_docker_environment | bool
    )
