---
- name: Reload systemd
  systemd:
    daemon_reload: true
  when: not (
    molecule_docker_environment is defined
    and molecule_docker_environment | bool
    )

- name: Start renew timer
  systemd:
    name: "{{ renew_service_name }}.timer"
    state: started
  when: not (
    molecule_docker_environment is defined
    and molecule_docker_environment | bool
    )
