---
dependency:
  name: galaxy
  options:
    role-file: ./molecule/shared/requirements.yml

driver:
  name: vagrant
  provider:
    name: virtualbox

platforms:
  - name: ansible-letsencrypt-xenial
    box: ubuntu/xenial64
  - name: ansible-letsencrypt-bionic
    box: ubuntu/bionic64
  - name: ansible-letsencrypt-focal
    box: ubuntu/focal64
  - name: ansible-letsencrypt-stretch
    box: debian/stretch64
  - name: ansible-letsencrypt-buster
    box: debian/buster64

provisioner:
  name: ansible
  playbooks:
    prepare: ../shared/prepare.yml
    converge: ../shared/converge.yml
    verify: ../shared/verify.yml
  inventory:
    host_vars:
      ansible-letsencrypt-stretch:
        ansible_python_interpreter: /usr/bin/python3
      ansible-letsencrypt-buster:
        ansible_python_interpreter: /usr/bin/python3

verifier:
  name: ansible
