---
- name: Converge
  hosts: all
  become: true

  roles:
    - role: ansible-letsencrypt
      letsencrypt_email: XXXX@gmail.com
      letsencrypt_volume: /srv/letsencrypt
      letsencrypt_sites:
        - domain: my.domain.one
          dry_run: true
          test_cert: false
          ignore: true
      letsencrypt_force_cert_creation: true
