---
- name: Converge
  hosts: all
  become: true

  roles:
    - role: ansible-letsencrypt
      email: XXXX@gmail.com
      volume: /srv/letsencrypt
      sites:
        - domain: my.domain.one
          dry_run: true
          test_cert: false
          ignore: true
      force_cert_creation: true
