---
- name: Verify
  hosts: all
  become: true

  tasks:
    - name: Should have created working directory
      file:
        path: /opt/letsencrypt
        state: directory
      register: working_directory
      failed_when: working_directory.changed

    - name: Should have created volume
      file:
        path: /srv/letsencrypt
        state: directory
      register: volume
      failed_when: volume.changed

    - name: Should have created renew service
      slurp:
        src: /etc/systemd/system/letsencrypt.renew.service
      register: renew_service
      failed_when:
        not renew_service.content == ( expected_content | b64encode )
      vars:
        expected_content: |
          [Unit]
          Description = letsencrypt certificate renew service
          
          [Service]
          ExecStartPre = -/usr/bin/docker pull certbot/certbot:latest
          
          ExecStart = /usr/bin/docker run \
                                      --rm \
                                      --name letsencrypt \
                                      --volume "/srv/letsencrypt/config:/etc/letsencrypt" \
                                      --volume "/srv/letsencrypt/data:/var/lib/letsencrypt" \
                                      --volume "/srv/letsencrypt/www:/www" \
                                      --volume "/var/log/letsencrypt:/var/log/letsencrypt" \
                                      certbot/certbot:latest \
                                      renew -a webroot \
                                            --webroot-path=/www \
                                            --non-interactive \
                                            --email XXXX@gmail.com \
                                            --agree-tos \
                                            --rsa-key-size 4096
          
          ExecStopPost  = -/bin/systemctl start nginx.reload
          
          Restart = no
          TimeoutSec = 3600

    - name: Should have created renew timer
      slurp:
        src: /etc/systemd/system/letsencrypt.renew.timer
      register: renew_timer
      failed_when:
        not renew_timer.content == ( expected_content | b64encode )
      vars:
        expected_content: |
          [Unit]
          Description=Run daily letsencrypt renew
          
          [Timer]
          OnCalendar = daily
          Persistent=true
          
          [Install]
          WantedBy=timers.target

    - name: Should have created logrotate config
      slurp:
        src: /etc/logrotate.d/letsencrypt
      register: logrotate_config
      failed_when:
        not logrotate_config.content == ( expected_content | b64encode )
      vars:
        expected_content: |
          /var/log/letsencrypt/*.log {
          	rotate 8
          	weekly
          	compress
          	missingok
          }
